---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: generic/freebsd12
    driver:
      network:
        - ["forwarded_port", {guest: 25565, host: 25565}]
      synced_folders: 
       - [".", "/vagrant", "disabled: true"]
      customize:
        cpus: 2
        memory: 5120

suites:
  - name: default
    data_bags_path: "test/integration/default/databags"
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      forge_server:
        installer:
          version: "1.14.4-28.0.45"
        mods:
          listing:
            jei:
              comment: Just Enough Items (JEI) (by mezz)
              version: 1.14.4-6.0.0.10
              project_id: '238222'
              file_id: '2757672'
              server: false
              client: true
              has_config_recipe: false
              ignore_in_test: false
              twitch_extra_opts:
                required: true

