---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: freebsd-10.3
    driver:
      synced_folders: 
       - [".", "/vagrant", "disabled: true"]
      customize:
        cpus: 2
        memory: 5120

suites:
  - name: default
    run_list:
      - recipe[forge_server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      forge_server:
        installer:
          version: "1.11.2-13.20.1.2386"
        installed:
          version: "1.12.2-14.23.2.2611"
  - name: with_map
    run_list:
      - recipe[forge_server::mod_dynmap]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      forge_server:
        installer:
          version: "1.12.2-14.23.2.2611"
