---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: generic/freebsd11
    driver:
      network:
        - ["forwarded_port", {guest: 25565, host: 25565}]
      synced_folders: 
       - [".", "/vagrant", "disabled: true"]
      customize:
        cpus: 2
        memory: 5120

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[forge_server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      forge_server:
        installer:
          version: "1.12.2-14.23.2.2611"
